name: CI

on:
  pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Print workspace info
        run: |
          pnpm -v
          pnpm -w list

      - name: Check (Biome lint + format check)
        run: pnpm -w run check

      - name: Build (Turbo)
        run: pnpm -w run build
